version: '3'
services:
  frontend:
    build:
      context: .
      target: frontend
  
  backend:
    build:
      context: .
      target: backend
    ports:
      - "8081:8081"
    volumes:
      - db:/app/db.sqlite3

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend

volumes:
  db:
